# ##############################################################################
# # File: docker-compose.yml                                                   #
# # Project: postfix                                                           #
# # Created Date: 2024/11/24 12:03:15                                          #
# # Author: realjf                                                             #
# # -----                                                                      #
# # Last Modified: 2024/11/24 12:08:18                                         #
# # Modified By: realjf                                                        #
# # -----                                                                      #
# #                                                                            #
# ##############################################################################

version: '3.8'
services:
  smtp-server:
    #container_name: smtp-server
    build:
      context: .
      args:
        EMAIL: ${EMAIL}
        EMAIL_PASSWORD: ${EMAIL_PASSWORD}
        MAIL_NAME: ${MAIL_NAME}
        SMTP_DOMAIN: ${SMTP_DOMAIN}
        SMTP_PORT: ${SMTP_PORT}
    ports:
      - ${PORT}:25
    volumes:
      - ./main.cf: 
